use std::{cell::RefCell, rc::Rc};

use crate::{
    attribute::Attribute,
    classfile::Field,
    instructions::{bytecode_reader::BytecodeReader, Instruction},
    runtime_data_area::{Frame, Thread},
};

pub fn interpret(method_info: Field) {
    let code_attr = method_info.get_code().unwrap();
    if let Attribute::Code {
        cp,
        max_stack,
        max_locals,
        code,
        exception_table,
        attributes,
    } = code_attr
    {
        let mut thread = Rc::new(RefCell::new(Thread::new()));
        let mut frame = Frame::new(
            *max_locals as usize,
            *max_stack as usize,
            Rc::downgrade(&thread),
        );
        thread.borrow_mut().push_frame(frame);
        loop_interpret(thread, code.clone());
    }
}

pub fn loop_interpret(thread: Rc<RefCell<Thread>>, bytecode: Vec<u8>) {
    let mut frame = thread.borrow_mut().pop_frame();
    let mut reader = BytecodeReader::new(bytecode);
    loop {
        let pc = frame.next_pc();
        thread.borrow_mut().set_pc(pc);
        reader.reset(pc);
        let opcode = reader.read_u8();
        let mut instruction = match opcode {
            0x00 => Instruction::Nop,
            0x01 => Instruction::AconstNull,
            0x02 => Instruction::IconstM1,
            0x03 => Instruction::Iconst0,
            0x04 => Instruction::Iconst1,
            0x05 => Instruction::Iconst2,
            0x06 => Instruction::Iconst3,
            0x07 => Instruction::Iconst4,
            0x08 => Instruction::Iconst5,
            0x09 => Instruction::Lconst0,
            0x0a => Instruction::Lconst1,
            0x0b => Instruction::Fconst0,
            0x0c => Instruction::Fconst1,
            0x0d => Instruction::Fconst2,
            0x0e => Instruction::Dconst0,
            0x0f => Instruction::Dconst1,
            0x10 => Instruction::Bipush(0),
            0x11 => Instruction::Sipush(0),
            // 0x12 => Instruction::Ldc(0),
            // 0x13 => Instruction::LdcW(0),
            // 0x14 => Instruction::Ldc2W(0),
            0x15 => Instruction::Iload(0),
            0x16 => Instruction::Lload(0),
            0x17 => Instruction::Fload(0),
            0x18 => Instruction::Dload(0),
            0x19 => Instruction::Aload(0),
            0x1a => Instruction::Iload0,
            0x1b => Instruction::Iload1,
            0x1c => Instruction::Iload2,
            0x1d => Instruction::Iload3,
            0x1e => Instruction::Lload0,
            0x1f => Instruction::Lload1,
            0x20 => Instruction::Lload2,
            0x21 => Instruction::Lload3,
            0x22 => Instruction::Fload0,
            0x23 => Instruction::Fload1,
            0x24 => Instruction::Fload2,
            0x25 => Instruction::Fload3,
            0x26 => Instruction::Dload0,
            0x27 => Instruction::Dload1,
            0x28 => Instruction::Dload2,
            0x29 => Instruction::Dload3,
            0x2a => Instruction::Aload0,
            0x2b => Instruction::Aload1,
            0x2c => Instruction::Aload2,
            0x2d => Instruction::Aload3,
            0x2e => Instruction::Iaload,
            0x2f => Instruction::Laload,
            0x30 => Instruction::Faload,
            0x31 => Instruction::Daload,
            0x32 => Instruction::Aaload,
            // 0x33 => Instruction::Baload,
            // 0x34 => Instruction::Caload,
            // 0x35 => Instruction::Saload,
            0x36 => Instruction::Istore(0),
            0x37 => Instruction::Lstore(0),
            0x38 => Instruction::Fstore(0),
            0x39 => Instruction::Dstore(0),
            0x3a => Instruction::Astore(0),
            0x3b => Instruction::Istore0,
            0x3c => Instruction::Istore1,
            0x3d => Instruction::Istore2,
            0x3e => Instruction::Istore3,
            0x3f => Instruction::Lstore0,
            0x40 => Instruction::Lstore1,
            0x41 => Instruction::Lstore2,
            0x42 => Instruction::Lstore3,
            0x43 => Instruction::Fstore0,
            0x44 => Instruction::Fstore1,
            0x45 => Instruction::Fstore2,
            0x46 => Instruction::Fstore3,
            0x47 => Instruction::Dstore0,
            0x48 => Instruction::Dstore1,
            0x49 => Instruction::Dstore2,
            0x4a => Instruction::Dstore3,
            0x4b => Instruction::Astore0,
            0x4c => Instruction::Astore1,
            0x4d => Instruction::Astore2,
            0x4e => Instruction::Astore3,
            0x4f => Instruction::Iastore,
            0x50 => Instruction::Lastore,
            0x51 => Instruction::Fastore,
            0x52 => Instruction::Dastore,
            0x53 => Instruction::Aastore,
            // 0x54 => Instruction::Bastore,
            // 0x55 => Instruction::Castore,
            // 0x56 => Instruction::Sastore,
            0x57 => Instruction::Pop,
            0x58 => Instruction::Pop2,
            0x59 => Instruction::Dup,
            0x5a => Instruction::DupX1,
            0x5b => Instruction::DupX2,
            0x5c => Instruction::Dup2,
            0x5d => Instruction::Dup2X1,
            0x5e => Instruction::Dup2X2,
            0x5f => Instruction::Swap,
            0x60 => Instruction::Iadd,
            0x61 => Instruction::Ladd,
            0x62 => Instruction::Fadd,
            0x63 => Instruction::Dadd,
            0x64 => Instruction::Isub,
            0x65 => Instruction::Lsub,
            0x66 => Instruction::Fsub,
            0x67 => Instruction::Dsub,
            0x68 => Instruction::Imul,
            0x69 => Instruction::Lmul,
            0x6a => Instruction::Fmul,
            0x6b => Instruction::Dmul,
            0x6c => Instruction::Idiv,
            0x6d => Instruction::Ldiv,
            0x6e => Instruction::Fdiv,
            0x6f => Instruction::Ddiv,
            0x70 => Instruction::Irem,
            0x71 => Instruction::Lrem,
            0x72 => Instruction::Frem,
            0x73 => Instruction::Drem,
            0x74 => Instruction::Ineg,
            0x75 => Instruction::Lneg,
            0x76 => Instruction::Fneg,
            0x77 => Instruction::Dneg,
            0x78 => Instruction::Ishl,
            0x79 => Instruction::Lshl,
            0x7a => Instruction::Ishr,
            0x7b => Instruction::Lshr,
            0x7c => Instruction::Iushr,
            0x7d => Instruction::Lushr,
            0x7e => Instruction::Iand,
            0x7f => Instruction::Land,
            0x80 => Instruction::Ior,
            0x81 => Instruction::Lor,
            0x82 => Instruction::Ixor,
            0x83 => Instruction::Lxor,
            0x84 => Instruction::Iinc(0, 0),
            0x85 => Instruction::I2l,
            0x86 => Instruction::I2f,
            0x87 => Instruction::I2d,
            0x88 => Instruction::L2i,
            0x89 => Instruction::L2f,
            0x8a => Instruction::L2d,
            0x8b => Instruction::F2i,
            0x8c => Instruction::F2l,
            0x8d => Instruction::F2d,
            0x8e => Instruction::D2i,
            0x8f => Instruction::D2l,
            0x90 => Instruction::D2f,
            // 0x91 => Instruction::I2b,
            // 0x92 => Instruction::I2c,
            // 0x93 => Instruction::I2s,
            0x94 => Instruction::LCmp,
            0x95 => Instruction::FCmpL,
            0x96 => Instruction::FCmpG,
            0x97 => Instruction::DCmpL,
            0x98 => Instruction::DCmpG,
            0x99 => Instruction::IfEq(0),
            0x9a => Instruction::IfNe(0),
            0x9b => Instruction::IfLt(0),
            0x9c => Instruction::IfGe(0),
            0x9d => Instruction::IfGt(0),
            0x9e => Instruction::IfLe(0),
            0x9f => Instruction::IficmpEq(0),
            0xa0 => Instruction::IficmpNe(0),
            0xa1 => Instruction::IficmpLt(0),
            0xa2 => Instruction::IficmpGe(0),
            0xa3 => Instruction::IficmpGt(0),
            0xa4 => Instruction::IficmpLe(0),
            0xa5 => Instruction::IfacmpEq(0),
            0xa6 => Instruction::IfacmpNe(0),
            0xa7 => Instruction::Goto(0),
            // 0xa8 => Instruction::Jsr(0),
            // 0xa9 => Instruction::Ret(0),
            0xaa => Instruction::TableSwitch {
                default_offset: 0,
                low: 0,
                high: 0,
                offsets: vec![],
            },
            0xab => Instruction::LookupSwitch {
                default_offset: 0,
                npairs: 0,
                match_offsets: vec![],
            },
            // 0xac => Instruction::Ireturn,
            // 0xad => Instruction::Lreturn,
            // 0xae => Instruction::Freturn,
            // 0xaf => Instruction::Dreturn,
            // 0xb0 => Instruction::Areturn,
            0xb1 => Instruction::Return,
            // 0xb2 => Instruction::GetStatic(0),
            // 0xb3 => Instruction::PutStatic(0),
            // 0xb4 => Instruction::GetField(0),
            // 0xb5 => Instruction::PutField(0),
            // 0xb6 => Instruction::InvokeVirtual(0),
            // 0xb7 => Instruction::InvokeSpecial(0),
            // 0xb8 => Instruction::InvokeStatic(0),
            // 0xb9 => Instruction::InvokeInterface(0, 0),
            // 0xba => Instruction::InvokeDynamic(0),
            // 0xbb => Instruction::New(0),
            // 0xbc => Instruction::NewArray(0),
            // 0xbd => Instruction::AnewArray(0),
            // 0xbe => Instruction::ArrayLength,
            // 0xbf => Instruction::Athrow,
            // 0xc0 => Instruction::CheckCast(0),
            // 0xc1 => Instruction::InstanceOf(0),
            // 0xc2 => Instruction::MonitorEnter,
            // 0xc3 => Instruction::MonitorExit,
            0xc4 => Instruction::Wide(Box::new(Instruction::Nop)),
            // 0xc5 => Instruction::MultiANewArray(0, 0),
            0xc6 => Instruction::IfNull(0),
            0xc7 => Instruction::IfNonNull(0),
            0xc8 => Instruction::GotoW(0),
            // 0xc9 => Instruction::JsrW(0),
            // 0xca => Instruction::Breakpoint,
            // 0xfe => Instruction::ImpDep1,
            // 0xff => Instruction::ImpDep2,
            _ => panic!("Unsupported opcode: {}", opcode),
        };
        println!("opcode: {}", opcode);
        instruction.fetch_operands(&mut reader);
        instruction.execute(&mut frame);
    }
}

mod test {
    // use crate::classfile::ClassFile;

    // #[test]
    // fn test_interpret() {
    //     let class_file = ClassFile::new("src/testdata/Hello.class");
    //     let main_method = class_file.get_main_method();
    //     crate::interpreter::interpret(main_method);
    // }
}